public with sharing class ContactHelperExtension {
    public static void updateDescription(List<Contact> contactToUpdated) {
        List<Contact> contactUpdated = new List<Contact>{};
        for(Contact : updateContactDescription : contactToBeUpdated)
        {
            Contact updatedContact = new Contact();
            updateContact.id = updateContactDescription.id;
            updateContact.Description= 'Contact Description';
            insert 
        }
    }
}